### ISSUE TITLE
Mobs become real / drop items.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#155]
Testing on Paper 1.20.6 Build 148
If you teleport around fast enough, the mob becomes real.
You can then teleport back to it, kill it and get it's drops.
Likely it is getting unloaded as it teleports into an unloading chunk.

I also believe that paper had a feature to delay chunk loaded but that appears to have been dropped in 1.21, although this bug report is for Paper 1.20.6 Build 148.

**Comment by Techirion** [comment]
Actually we had players reporting this on 1.20.4 already.

**Comment by Arnuh** [comment]
I've noticed this a couple times during my usual testing but I assumed it was a bug with server shutdowns.

I can only imagine the cause would be the pet being left in a chunk that is unloaded so when it gets loaded again it just creates a 'clean'(non echopet entity)

**Comment by Arnuh** [comment]
Might require overriding `shouldBeSaved` ? I don't really have a setup where I can reliably reproduce this but this would prevent `storeChunkSections` in `PersistentEntitySectionManager` from saving it?

I also swear echopet use to have some unload event being checked but I guess not? that's an option to investigate also.

**Comment by electronicboy** [comment]
Yes, especially with how active minecraft is to unloading entities/chunks, waiting 20 ticks to teleport the entity is just extreme;

I threw together a quick hack fix locally which adds a chunk ticket (to ensure it doesn't unload in the meantime) and teleports *an* tick later (removing the ticket in the process), as I see no sane reason to go for 20 ticks unless you're expecting plugins to do something stupid, but, even that would cause issues with the current logic from what I can see

if I was more invested, I'd probably just despawn the entity then and there, and then queue up a task to respawn it in a few ticks after they've teleported (or not), if you want to deal with a player being teleported 200 times, might want to add some logic to delay any existing respawn attempt of the entity and respawn it then and there

I also added a PDC key onto the entity so that we can detect it in the applicable chunk events, for some reason that broke, I'd guess maybe some changes to how those events fire

**Comment by electronicboy** [comment]
overriding shouldBeSaved() would prevent them from ever being to save, I did consider looking into that, but was worried it would be too verbose of a change set to maintain

**Comment by Arnuh** [comment]
> overriding shouldBeSaved() would prevent them from ever being to save, I did consider looking into that, but was worried it would be too verbose of a change set to maintain

It's not that bad of a change as I already copypaste a set of overrides with the way I do new pets, I applied it locally to investigate it as a fix.

Also did a quick check if it'd be okay to just set a removal reason which would be easier to maintain. Probably a more riskier but cleaner approach. Not entirely sold on it when `shouldBeSaved` is an overall safer option

Also as a note, anything tick delay related in echopet is mostly left because I'm not confident I can confirm no regressions

**Comment by Arnuh** [comment]
You guys can test if you want. I already did the work so I might as well offer it to anyone using the plugin.

Best result, issue is fixed. Worst result: I just revert the commit with a proper fix

**Comment by electronicboy** [comment]
> It's not that bad of a change as I already copypaste a set of overrides with the way I do new pets, I applied it locally to investigate it as a fix.

that's good then, setting a removal reason would potentially violate some checks, i.e. isAlive()

There is potentially a double bug here, but, I've not double tested, I'd imagine that the pet is "lost" into the unloaded chunk, this will fix the risk of the entity coming back as a real entity, but, will mean that people teleporting in fast succession will lose their pets, not as big of a deal, but 🤷

**Comment by andrewkm** [comment]
> You guys can test if you want. I already did the work so I might as well offer it to anyone using the plugin.
> 
> Best result, issue is fixed. Worst result: I just revert the commit with a proper fix

1.21 support works good! Thanks!
@electronicboy said we're going to be using a different method for this patch I believe though, he may be able to elaborate more, I'm just the tester lol.

**Comment by andrewkm** [comment]
Sent you a Discord DM with more information. :)

**Comment by electronicboy** [comment]
so, looking at it, I had a patch which made us teleport the entity after the 20 ticks rather than recreating it, I'm not sure why I have that patch, I think recreating the entity was losing some transient state set by players and something, and that relied on the behaviour of papers delayed chunk unloading logic 

I recall entities ending up in the world outside of this in some cases, so, this is a good thing to deal with anyway, I've just got a patch which makes it more likely to occur

**Comment by andrewkm** [comment]
The patches are good and working, and there was one final issue, but it was solved with:
https://github.com/PaperMC/Paper/issues/10965
https://github.com/PaperMC/Paper/commit/a594d182e49e6f5a788075243bbff97f86b1edd7

Hurray! :)
