### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by AshourAziz** [Arnuh/EchoPet#16]
I'm having so many errors from compiling because of missing dependencies as some of the repo's have gone.

I've fixed everything but I cannot get the proper VanishNoPacket repo setup, do you have a compiled jar for release or have a repo that contains VanishNoPacket?

**Comment by RickyB98** [comment]
@AshourAziz Since I didn't need VanishNoPacket I got rid of that repo from the pom.xml file and removed all dependency from it. My problem is that I can't find other repositories or packages, like `com.codingforcookies.robert.core` and I couldn't find these anywhere on the internet. Perhaps @Borlea could tell us what repos to compile manually and where to find them.

**Comment by Arnuh** [comment]
I've added Robert to my [github](https://github.com/Arnuh/Robert).
