### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by TheIntelloBox** [Arnuh/EchoPet#18]

**Comment by Arnuh** [comment]
I'll look into it. Surprised everyone hasn't moved on.

**Comment by TheIntelloBox** [comment]
Yeah. :)

**Comment by Arnuh** [comment]
I'll give a bit of an update. Had some issues starting with setting everything up again(First actual issue since reformatting...) but I got it almost all working except some weird error so I can't properly compile and test the first attempt

Also the update introduced some changes to how we have to override entities and I hope my first attempt will work but I'll likely see sometime tomorrow assuming I can fix the current error im getting with maven.

And another thing I can't actually compile 1.8 > 1.11 jars even with the buildtools updated for the specific version I'm trying to build so hopefully no one excepts update for those versions because I can't actually give them..

**Comment by TheIntelloBox** [comment]
You should do 2 jars: the 1.13 version, and the 1.8-1.12 version. :)

**Comment by TNTUP** [comment]
Agreed, 1,.13 and 18-1.12, I'm locked to 1.12.2 until all plugins are updated, but 1.13 is full of bugs, and even 1.13.1 is soon

**Comment by Arnuh** [comment]
I don't really support going less than latest, or if latest is too new I'm fine with 1 below.

issue is buildtools doesn't work when I select revs 1.8 > 1.11, and since I reformatted I don't have them locally and since I don't really care about supporting such versions or using some 3rd party repo to get them.

I can just let people either use 1.12 version or compile the project themselves if they want to stay on outdated versions.

**Comment by Arnuh** [comment]
After couple hours in past 3 days dealing with maven errors.. Atleast I got this 
![javaw_2018-08-02_00-44-02](https://user-images.githubusercontent.com/2877803/43566976-84473834-95ed-11e8-9c06-b543dab5fc22.png)

A new thing in 1.13 is the entity class now uses a EntityTypes, World parameter. If the entity type is null the mob is invisible, if the entity type is incorrect for what you spawned it crashes the client.

I assume best way to do this will be to manually insert the EntityType in each class.

I just looked at amount of changes with items. I'm 100% dropping any support for anything lower than 1.13

**Comment by TheIntelloBox** [comment]
No problem sir, glad to hear that EchoPet is working. :)

**Comment by Arnuh** [comment]
[Here is latest version](https://mega.nz/#!usgRgI6L!tzT26aINr_8SYPg4VoVSbvyT-uZqhtn-bIs_RWoe7Kk)
Riding seems to work. I redid a bunch of material shit and forced it to use 1.13 cause spigots setup for legacy material support is a mess for checking if an item is same type.

Haven't added any new mobs yet. That'll have to wait for whenever I work on it more.

**Comment by TNTUP** [comment]
I'll give it a try on my 1.13 testiing server, but sadly there's chances I cannot pass to 1.13 due to outdated plugins xD

**Comment by johngonole** [comment]
Arnuh, thanks for updating the plugin.   Really appreciate it.   Will try it out soon and let you know what bugs pop up.

**Comment by Arnuh** [comment]
[New link](https://mega.nz/#!usgRgI6L!tzT26aINr_8SYPg4VoVSbvyT-uZqhtn-bIs_RWoe7Kk)
Has all the new commits. Basics for every new 1.13 mob is added.

**Comment by Arnuh** [comment]
Closing since 1.13-R2 is released and 1.13-R1 is deprecated. All discussion goes to #21
