### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by TNTUP** [Arnuh/EchoPet#26]
Title says it. To give you support and love <3

**Comment by andrewkm** [comment]
Oh my word @Arnuh still updating this lol.

**Comment by Arnuh** [comment]
@andrewkm I just check in on minecraft every once in awhile.. Project is simple enough that it takes a bit of work every once in awhile to make it stable enough that not too many big issues exist.

Project is definitely starting to show age due to new monsters coming out and requiring extra support. Stuff like fish might need something, and new flying mobs..

**Comment by andrewkm** [comment]
@arnuh you may as well slap this on spigot premium and get $$$ for updates tbh lol MC has yet to have a proper pet plugin past echo

**Comment by Arnuh** [comment]
@andrewkm MC dev is pretty meh.. I'll give it to people for free as I have no reason to not.

**Comment by andrewkm** [comment]
@arnuh you want a Jenkins for this? Since I notice you keep providing download links in random places.
