### ISSUE TITLE
WorldEdit Vectors NPEs

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#34]
Environment:
Spigot 1.13.2
EchoPet: Build [8](https://ci.ecocitycraft.com/job/EchoPet/8/)
World Edit: Build [3943](http://builds.enginehub.org/job/worldedit/10618)
World Guard: Build [1756](http://builds.enginehub.org/job/worldguard/10609)

WorldEdit still shooting NPEs on every /pet command:
https://pastebin.com/raw/L0ncnqj3

**Comment by Arnuh** [comment]
I checked both the 7.0.0 beta and the latest grabbed from maven and both have the BukkitAdapter.asVector

Check build 3943.. has it but returns a Vector3..

Also just checked latest world edit on repo.. also vector3.. I swear if this shit changed again.

**Comment by Arnuh** [comment]
Deleted my worledit and worldguard maven folder to force them to update.

Nothing changed so I wont be fixing this. I'll accept any PR tho.

Issue is likely because the worldguard on the public repo uses an outdated worldedit.

**Comment by me4502** [comment]
The version you're building against is before the vector refactor.

**Comment by andrewkm** [comment]
So even if using a /lib/ with the two WE/WG libraries (which will need to be changed in the pom to work on this jenkins) it's still throwing NPE's on /pet command, which @me4502 says your source would still need a couple updates to get echopet fully onto the new WE/WG.

Rip. That's enough battling this for today, spent way more time than I should on this lol. Bed time.

**Comment by Sandukhan** [comment]
Hi,
i have the same problem with echopet and newer worldedit builds:
https://pastebin.com/cX0zKqkk

EchoPet v1.0.4-SNAPSHOT-b
Worldedit 7.0.0-SNAPSHOT;3937-24800a6
Worldguard 7.0.0-SNAPSHOT;1754-9169653

http://builds.enginehub.org/job/worldedit?branch=master

Its not just a problem of echopets, a lot of my plugins dont work properly because that.

**Comment by andrewkm** [comment]
My team will be working on fixing all EchoPet issues in the coming future. First have to finish one other major project and then we’ll get to this.

Once complete will provide the update to this repo as well =)

**Comment by Arnuh** [comment]
Ok somehow I mentioned the wrong issue so https://github.com/Arnuh/EchoPet/commit/c608a94212d3ddaacd6e459606dbcb5e2f2e0611

Someone finally pushed an updated worldguard to the repo so it finally grabbed a newer worldedit 🙏 I'll look into the ender dragon issue too now that I already have minecraft open

**Comment by andrewkm** [comment]
Ayyy :)

**Comment by me4502** [comment]
Nothing was changed on the repo - glad you’ve gotten it resolved though

**Comment by Arnuh** [comment]
@me4502 The issue was pretty clear imo.. WorldEdit was updated with the latest vector changes but the newest worldguard(at the time) was still using an outdated(or broken?) worldedit so it didn't supply the latest API methods causing this issue.

And maven doesn't just randomly grab newer depends it wasn't built on, this is why both jenkins & I had the latest worldguard(from the repo) but that was using an outdated worldedit allowing us to build it fine.

**Comment by me4502** [comment]
Nah, the WorldGuard build was pushed to update to the Vector changes at the same time as WorldEdit. WorldGuard had the correct API methods available to it.

And yeah, Maven does do that, but that's not really related to the issue.

For most people it was working fine, for a small subset of people they were receiving invalid versions when using Maven, which I believe is related to the codemc repo serving an invalid WorldEdit jar which they removed just before you said it was fixed.
