### ISSUE TITLE
default config messed up?

### ISSUE THREAD

**Issue by PhanaticD** [Arnuh/EchoPet#42]
https://gyazo.com/c68d7143bf27e9f890e6ddf3ce544024

**Comment by Arnuh** [comment]
No idea what caused this but it made me try and correct the descriptions.

**Comment by andrewkm** [comment]
@Arnuh can confirm default config is completely fucked and not loading.
https://pastebin.com/raw/AE1wHZJd

Old configs mess up and become this:
https://pastebin.com/aWpAFFQ3

Lines 66-82

Can you revert/fix this up:
https://github.com/Arnuh/EchoPet/commit/8f4b29fb0c6fddf4185e7e15663691f9ece618e5

**Comment by Arnuh** [comment]
With some testing the issue came down to 2 things.
The strings were too long and the config api didn't like the use of `:` in comments(or at least with how dsh does them).

This fix is on the 1.14 branch which as of writing this is far away from even requiring external testing so if you need this for 1.13 you're best off grabbing latest master & applying changes yourself.

**Comment by andrewkm** [comment]
@arnuh yeah, nah we don't need the change to be honest at this time. I've simply reverted for now on our 1.13.2 servers. I'll update later when I begin my 1.14 upgrade, which could easily be weeks lol.
