### ISSUE TITLE
Improve settings of 1.13 mobs such as turtle, pufferfish and tropical fish

### ISSUE THREAD

**Issue by Blatower21** [Arnuh/EchoPet#45]
Turtles: Add possibility of having a baby turtle

Pufferfish: Like slime or magmacube, have the chance of select the pufferfish size (small, medium and big one)

Tropical Fish: Add possibility of select the skin of the tropical fish you have, right now you only can have the white one and could be amazing if it was like horse, sheep or llama skins that you can select the skin!

**Comment by TNTUP** [comment]
Noticed when I couldn't select the pufferfish's sizes, its not implemented for now xD Keep the good work all <3

EDIT: I noticed when using EchoPet for 1.13.2, mobs does not make their idle sound. Is this expected or its an issue on my side? No rush for the 1.13.2, was just reporting it here

**Comment by Arnuh** [comment]
Looks like Turtles got it automatically added with my new check for IAgeablePet
Did pufferfish one obviously

@TNTUP Create a separate issue

**Comment by TNTUP** [comment]
@Arnuh Ok will do, want me to delete my previous comment not to clutter this issue? (This message will be deleted aswell as soon you've seen it)

**Comment by Arnuh** [comment]
This should be done.. I just did colored patterns for the 'types' of tropical fish and if anyone has any suggestions for improving the material I'll accept ideas in #46.
Also half of the types are actually just the other half but large automatically set to true.. I kept all types while also having a toggle for large(which might actually be an issue now that I think of it because it wont update that petdata when you select the opposite method of enabling large/small)
