### ISSUE TITLE
Spawn in multiple pets. (Feature?)

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#69]
Would it be possible to allow users to spawn in multiple pets.

Or would this require far too much rewriting and overhaul? Would be a nice little feature if it’s not much to accomplish <3

`/pet <type> <type> <type>`

**Comment by Arnuh** [comment]
Probably too annoying to do this.

getPet just returns 1 pet so I would have to update every use of that
The command suggestion you gave is how riders work so that would have to be adjusted.
Saving uses "pet" and "rider" so it would have to be fixed up.. not too bad probably just swap to a list and set rider under the parent pet.

the getPet mess doesn't actually seem that bad.. Issue is all the commands only really support 1 pet(Where a majority of getPet calls are from)
