### ISSUE TITLE
1.12 release?

### ISSUE THREAD

**Issue by MineTheCube** [Arnuh/EchoPet#75]
Hi,
I'm looking for the 1.12 release, sadly it seems to have been removed from https://github.com/Arnuh/EchoPet/releases :/
I tried to compile from the `v1_12` branch but too many dependencies are missing from maven repositories.. so could you upload the .jar or tell me where I can find it?
Thanks!

**Comment by Arnuh** [comment]
I don't know how outdated the 1.12 branch is but https://github.com/Arnuh/EchoPet/tree/d41897cfbb8a6cd14248510b7bdd70c880f67c56 is the last commit.

Most depends should be on on my git profile or can be updated to the ones in the pom.

I wont care to build it for others as its a super old version that I would rather not have people using, nor do I care to support 1.12 again as the changes from 1.12 > 1.13 are too big for me to put in the effort.

Also the 1.12 release was just the src files which is why I deleted it.

**Comment by TNTUP** [comment]
> Hi,
> I'm looking for the 1.12 release, sadly it seems to have been removed from https://github.com/Arnuh/EchoPet/releases :/
> I tried to compile from the `v1_12` branch but too many dependencies are missing from maven repositories.. so could you upload the .jar or tell me where I can find it?
> Thanks!

I can provide my current 1.12.2 build I'm running on my legacy 1.12.2 server but I won't recommend it because it can contain bugs and I'm not responsible for it. Depends if im allowed to drop it here, but unless I don't have consent of Arnuh nothing will happen XD

**Comment by M4RC0Sx** [comment]
> 
> 
> > Hi,
> > I'm looking for the 1.12 release, sadly it seems to have been removed from https://github.com/Arnuh/EchoPet/releases :/
> > I tried to compile from the `v1_12` branch but too many dependencies are missing from maven repositories.. so could you upload the .jar or tell me where I can find it?
> > Thanks!
> 
> I can provide my current 1.12.2 build I'm running on my legacy 1.12.2 server but I won't recommend it because it can contain bugs and I'm not responsible for it. Depends if im allowed to drop it here, but unless I don't have consent of Arnuh nothing will happen XD

Please I need it.
