### ISSUE TITLE
Error with PlayerTeleportEvent to EchoPet and even crash server sometimes

### ISSUE THREAD

**Issue by Blatower21** [Arnuh/EchoPet#79]
Error: https://pastebin.com/C7abJmzk

Crash: https://pastebin.com/jb38Qhnr

Would be glad if it is solved, I know that Echopet is not being updated regularly but when you're able to do it!

**Comment by Arnuh** [comment]
I've seen a similar crash issue before. No clue how to reproduce it but maybe I can look to properly solving the infinite loops.

For the error.. that's a strange one assuming these lines match up https://github.com/Arnuh/EchoPet/blob/master/modules/EchoPet/src/com/dsh105/echopet/api/pet/Pet.java#L379

**Comment by Blatower21** [comment]
Hi, it just crashed again with the same crash error, I'm not sure of the exact condition for this to happen either :(

**Comment by Arnuh** [comment]
I honestly see 0 reason for this code and it is very obvious why it infinite looped.

Assuming this code actually does nothing in 1.15(maybe even before 1.15) then I guess I can just keep it empty for future versions. Some testing would be nice since I can only test by myself usually.

Wish I knew why it was required in older versions since I can only assume it was for some weird check.
