### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Arnuh/EchoPet#87]

**Comment by EliMapletalesMC** [comment]
Hey Arnuh,

I know i already gave the idea but I couldn't help but post this, as I remembered a better system for a reference in regards to armorstand pet variants and how it could be achieved.

Had a (possibly) better referenced idea for how this could be implemented. This is how NathanWolf's Magic Plugin adds variants of wands for his plugin. 
![magic ref](https://user-images.githubusercontent.com/65664977/123282552-77e0df00-d4bf-11eb-95c1-9dc23114a5c1.PNG)

There is a folder in magic plugin's base folder, called "wands". This is where wands added with options like: 

> icon: minecraft:stick{101} # - _makes the stick read custommodeldata number "10"_
It also includes other config options for that separate wand like, name, description, particles, etc.
All of which if there was a similar system like this in EchoPets would ideally have the ones i posted in the photo.

all the code for wands: https://github.com/elBukkit/MagicPlugin/tree/master/Magic/src/main/java/com/elmakers/mine/bukkit/wand

**Comment by Arnuh** [comment]
The information you've given seems good. I would like an example model to test this on when for when I can start working on this.

I have zero idea how this type of stuff works but I assume its a simple resource pack I would need?

**Comment by mtElijah** [comment]
Yeah a simple resource pack is all you would need. Which i have provided here:
[example.zip](https://github.com/Arnuh/EchoPet/files/6729639/example.zip)

Then if you want to get an idea of how the whole thing works (how the resource pack re-textures items in minecraft) i've also provided a description right here:
-----------------------------------------------------------------------
so here's the folder structure of a minecraft resource pack
(Containing custom pet models. Or really just any type of custom model)
(but for this example it's mainly going to be for pets). This is *slighty* important
when finding out which parts are linked together. So basically that means that
all 3d models have 2 parts. Model (no textures= the base shape) and then of course 
texutres (png files that map out what he model looks like at the end.) Like i could have 
a spongebob model but it looks just like a spongebob *SHAPE* without the yellow, white,
etc. colors that make it look like spongebob. Knowing that, there is a certain folder
structure to where you put models and texutres. The term "custommodeldata" to me just means
that you place/give a number on a base vanilla minecraft **item** (can't be a block) and then 
when you call that number alongside the base vanilla minecraft item in-game [with a command]
e.g. : /minecraft:give Arnuh minecraft:stick{CustomModelData:1}. It will ONLY call that number
and give you whatever 3d model you set to "1" for a stick. Each model is a .json file. Which isn't
as important. However, in the folder structure, under "models > item" (right there in the
base directory of that particular folder is are .json files PERTAINING to whichever **item**
you would like to apply custommodeldata to). So say i had a stick in mind that i wanted to
apply custom model data to. I would make "stick.json" file containing the json code here:

{
    "parent": "item/generated",
    "textures": {
        "layer0": "item/stick"
    },
    "overrides": [
        {"predicate": {"custom_model_data": 1}, "model": "item/pets/slime"}
    ]
}

all the top half stuff im not really quite sure about except where it starts at= layer0: "item/stick". That part
must match whatever your .json file is (that being in this case stick.json).

overrides just means it will override a stick item to the following "model": "item/pets/slime"
(Where in you would find under the folder strucutre "pets > slime.json". Where slime.json is called
to replace the stick textures. NOTE: All these models are made in blockbench (a free program
that anyone can use to make 3d models: pets, weapons, hats, etc.)


base: example\

- assets\
- pack.mcmeta (not as important. mainly defines the pack version and
> pack description= what it would say in the resource packs folder chooser in mc)

- under "assets" is \minecraft\

- under that is "\models\", then the following folder: "item" and then in the item folder
there is stick.json (or whatever item you choose to set custom model data to).

then also in "item" folder are other folders you would store/categorize for your 3d models
(in this case i stored a "pets" folder. and that's where i saved the slime pet (model only)
in= that being slime.json)

slime.json btw contains at the near beginning of it more json code that calls to it's model
to map out the texutres

as shown in this json code example (pay attention to "2", "3", "4", and "5")

"{
	"credit": "Made with Blockbench",
	"texture_size": [56, 56],
	"textures": {
		"2": "pets/black_concrete",
		"3": "pets/eyesnpcslime",
		"4": "pets/slimenpc",
		"5": "pets/greennpcout",
		"particle": "pets/greennpcout"
	},"

so as you can see it's all linked.
here's a video showcasing me using the re-textured stick (that looks now like a Slime pet=
because i editted that portion in blockbench as shown in the "headslot.png" screenshot) and placing it
on the headslot (USING armorstandtools) and standing next to it as an example. THEN my idea
is to once have those armorstands in game be ridable and hat-able. etc. with toggles
for things like invisibility/invicibility (so the armor stand doesn't break at all)
-----------------------------------------------------------------------

video: https://streamable.com/irkf5h
